[features]
seeds = false
skip-lint = false
[programs.localnet]
solana_nft_anchor = "4vhnHhm3DN5K4CYZCuGdneYCYZB7Zqs4sgeutZFXx8qS"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/thisbo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
